// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPSEDlzuoDRK5DxCK6yihYqq6aHq-FC8',
    appId: '1:379797807557:web:5292ec75b323c8d9b9ebac',
    messagingSenderId: '379797807557',
    projectId: 'order-f4efc',
    authDomain: 'order-f4efc.firebaseapp.com',
    storageBucket: 'order-f4efc.firebasestorage.app',
    measurementId: 'G-FSTZNKPD18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-FzVHniuP8NrBaEm0Pe7rBc-i5_AfWg',
    appId: '1:379797807557:android:b413c59f7b6b2785b9ebac',
    messagingSenderId: '379797807557',
    projectId: 'order-f4efc',
    storageBucket: 'order-f4efc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvzYfhHn-GjGKNXpmIiwYrBoEHG0c3Vy4',
    appId: '1:379797807557:ios:48f05e4f1b1858c8b9ebac',
    messagingSenderId: '379797807557',
    projectId: 'order-f4efc',
    storageBucket: 'order-f4efc.firebasestorage.app',
    iosBundleId: 'com.example.order',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvzYfhHn-GjGKNXpmIiwYrBoEHG0c3Vy4',
    appId: '1:379797807557:ios:48f05e4f1b1858c8b9ebac',
    messagingSenderId: '379797807557',
    projectId: 'order-f4efc',
    storageBucket: 'order-f4efc.firebasestorage.app',
    iosBundleId: 'com.example.order',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBPSEDlzuoDRK5DxCK6yihYqq6aHq-FC8',
    appId: '1:379797807557:web:56bc6e2f220d7bb8b9ebac',
    messagingSenderId: '379797807557',
    projectId: 'order-f4efc',
    authDomain: 'order-f4efc.firebaseapp.com',
    storageBucket: 'order-f4efc.firebasestorage.app',
    measurementId: 'G-Y00LMHY3MY',
  );
}
